name: weather
favicon: null
layout_spectrum: 0.46652038185857236
typography_spectrum: 0.7193710424471647
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.0017757527530193329
  lightness: 0.5441566030494869
  saturation: 0.13789423182606697
  rhythmicContrast: 0.8828780739568174
purpose: []
